---

metadatos:
  titulo: 'POSVERSO'
  dominio: 'posversobienal.com.ar'
  descripcion: 'POSVERSO . Bienal Internacional de Poesía Experimental de Argentina'
  claves: 'poesía, experimental, internacional, hotel dada, arte, posverso, art, poetry, junín, buenos aires, argentina'
  imagen_compartir: '/rec/grafica/logo-posverso_compartir.png'
  logo_posverso_a: '/rec/grafica/logo-posverso.svg'
  logo_posverso_b: '/rec/grafica/logo-posverso_completo.svg'
  texto_posverso: 'POSVERSO. Bienal Internacional de Poesía Experimental de Argentina.'
  texto_hoteldada: 'Hotel DaDA. Base de arte correo y poesía experimental.'
  logo_hoteldada_a: '/rec/grafica/logo-hoteldada.svg'
  logo_hoteldada_b: '/rec/grafica/logo-hoteldada_completo.svg'
  imagen_compartir: 'rec/grafica/logo-posverso_compartir.png'
  favicon: '/rec/grafica/favicon.svg'

emails:
  posverso: 'posversobienal@gmail.com'
  hoteldada: 'dadahotel@hotmail.com'
  pveducativo: 'educativo.posversobienal@gmail.com'
  pvweb: 'web.posversobienal@gmail.com'

urls:
  formulario_convocatoria:
    es: 'https://forms.gle/ky4dzY4MrhZSA9nx8'
    en: 'https://forms.gle/Mgq4FxMJQeDYYDra8'

  posversobienal: 'https://posversobienal.com.ar/'
  posverso_instagram: 'https://www.instagram.com/posverso_bienal'
  posverso_youtube: 'https://www.youtube.com/@PosversoBienal'

  hoteldada_web: 'http://www.hoteldadabase.org/'
  hoteldada_instagram: 'https://www.instagram.com/hoteldada_galeria_arte'
  hoteldada_facebook: 'https://www.facebook.com/profile.php?id=100063732964738'
  hoteldada_youtube: 'https://www.youtube.com/channel/UC4HS1EiLlyc4l0JDc8_BwFA'

  info_omar_khouri: 'http://www.antoniomiranda.com.br/poesia_visual/omar_khouri.html'
  info_cesar_espinosa: 'https://www.heterogenesis.com/H-45/EspinozaCas.htm'
  info_clemente_padin: 'https://www.museoreinasofia.es/sites/default/files/biblioteca/archivo-de-archivos/bibliografia_clemente_padin_2023.pdf'
  info_eduardo_antonio_vigo: 'http://www.cvaa.com.ar/03biografias/vigo_e.php'
  info_guillermo_deisler: 'http://guillermodeisler.cl/'
  info_dick_higgins: 'https://dickhiggins.org/'

  info_cau: 'https://www.centrodearte.unlp.edu.ar/'
  info_afa: 'https://po-ex.net/taxonomia/transtextualidades/metatextualidades-autografas/arquivo-fernando-aguiar-poesia-experimental-visual-performance-mail-art-fluxus-e-arte-conceptual/'
  info_bibliotec_floresta: 'https://www.simonemoraes.net/editora-biblioteca-floresta'
  info_arte_online: 'https://www.arte-online.net/'
  info_utsanga: 'https://www.utsanga.it/'
  info_be_cult: 'https://revistabecult.com.ar/'
  info_bienal_saco: 'https://bienalsaco.com/'
  info_casariolab: 'https://www.casariolab.art/'
  info_mundo_perfo: 'https://mundoperformance.net/'
  info_et_gilberto_mesa: 'https://etjunin-bue.infd.edu.ar/sitio/'
  info_cp_dante_balestro: 'https://www.instagram.com/dantebalestro/'
  info_atsa_junin: 'https://sanidadjunin.com.ar/'
  info_casa_pronto: 'https://www.instagram.com/casa.pronto/'
  info_par1000: 'https://www.instagram.com/par1000teatro/'
  info_conservatorio_perez_cruz: 'https://www.conservatorioperezcruz.com/'
  info_marea_cultura: 'https://www.instagram.com/mareaculturajunin/'
  info_la_voz_de_los_barrios: 'https://lavozdelosbarrios.com/'
  info_museo_historico: 'https://www.facebook.com/archivohistoricojunin'
  info_villa_alpina: 'https://www.instagram.com/villaalpina.junin/'
  info_casa_del_pueblo: 'https://www.facebook.com/casadelpueblojunin/'
  info_sociedad_italiana_unita: 'https://www.instagram.com/sociedad.italiana.junin/'
  info_bp_paz_y_trabajo: 'https://www.facebook.com/p/Biblioteca-popular-Paz-y-Trabajo-100064620377143/'
  info_unnoba: 'https://www.unnoba.edu.ar/'
  info_el_espacio: 'https://www.instagram.com/elespacioyoga'

menu:
  - titulo: 'BIENAL'
    url: ''
    submenu:
      - titulo: 'Acerca de la bienal'
        url: '/pag/acerca_de_la_bienal/'
      - titulo: 'Eje temático'
        url: '/pag/eje_tematico/'
      - titulo: 'Equipo curatorial'
        url: '/pag/equipo_curatorial/'
      - titulo: 'Curadores invitados'
        url: '/pag/curadores_invitados/'
      - titulo: 'Artistas homenajeados'
        url: '/pag/artistas_homenajeados/'
      - titulo: 'Convocatoria abierta'
        url: '/pag/convocatoria_abierta/'
      - titulo: 'Socios estratégicos'
        url: '/pag/socios_estrategicos/'

  - titulo: 'PROGRAMA'
    url: ''
    submenu:
      - titulo: 'Programa'
        url: '/pag/programa/'
      - titulo: 'Exhibición central'
        url: '/pag/exhibicion_central/'
      - titulo: 'Otras exhibiciones'
        url: '/pag/otras_exhibiciones/'
      - titulo: 'Proyectos colaterales'
        url: '/pag/proyectos_colaterales/'

  - titulo: 'PROGRAMA EDUCATIVO'
    url: ''
    submenu:
      - titulo: 'Evento teórico'
        url: '/pag/evento_teorico/'
      - titulo: 'Mediación educativa'
        url: '/pag/mediacion_educativa/'
      - titulo: 'Publicaciones'
        url: '/pag/publicaciones/'


  - titulo: 'SEDES'
    url: '/pag/sedes/'
  - titulo: 'ARTISTAS'
    url: ''
    submenu:
      - titulo: 'Invitados'
        url: '/pag/artistas_invitados/'
      - titulo: 'Seleccionados'
        url: '/pag/artistas_seleccionados/'
  - titulo: 'PRENSA'
    url: '/pag/prensa/'


idiomas_traducibles:
  en: 'English'
  pt: 'Português'
  fr: 'Français'
  de: 'Deutsch'
  zh-CN: '中文'
  ja: '日本語'


sedes:
  orden:
    - hotel_dada
    - maca
    - museo_historico
    - horno_de_grippo
    - fundacion_casa_pronto
    - villa_alpina
    - casa-taller_torviso-sarobe
    - centro_de_capacitacion_y_cultura_atsa
    - casa_popular_dante_balestro
    - centro_cultural_marea_cultura
    - conservatorio_de_musica_juan_r_perez_cruz
    - sociedad_italiana
    - biblioteca_paz_y_trabajo
    - par1000_aula_teatro
    - ccp_horacio_alonso
    - comedor_los_totoreros
    - escuela_de_arte_xul_solar
    - escuela_de_educacion_artistica_victor_grippo
    - escuela_de_teatro_gilberto_mesa
    - unnoba_alicia_moreau_de_justo
    - el_espacio

  nombres:
    biblioteca_paz_y_trabajo: 'Biblioteca Popular Paz y Trabajo'
    casa-taller_torviso-sarobe: 'Casa Taller Torviso-Sarobe'
    casa_popular_dante_balestro: 'Casa Popular Dante Balestro'
    ccp_horacio_alonso: 'Casa de la Cultura Popular "Horacio Alonso"'
    centro_cultural_marea_cultura: 'Centro Cultural Marea Cultura'
    centro_de_capacitacion_y_cultura_atsa: 'Centro de Capacitación y Cultura ATSA'
    comedor_los_totoreros: 'Comedor "Los Totoreros"'
    conservatorio_de_musica_juan_r_perez_cruz: 'Conservatorio de Música "Juan R. Pérez Cruz"'
    el_espacio: 'El Espacio'
    escuela_de_arte_xul_solar: 'Escuela de Arte "Xul Solar"'
    escuela_de_educacion_artistica_victor_grippo: 'Escuela de Educación Artística "Victor Grippo"'
    escuela_de_teatro_gilberto_mesa: 'Escuela Provincial de Teatro "Gilberto A. Mesa"'
    espacio_publico: 'Espacio público'
    fundacion_casa_pronto: 'Fundación Casa Pronto'
    horno_de_grippo: 'Horno de Grippo'
    hotel_dada: 'HOTEL DADA Base de Arte Correo y Poesía Experimental'
    maca: 'MACA Museo de Arte Contemporáneo Argentino "Víctor Grippo"'
    museo_historico: 'Museo Histórico'
    par1000_aula_teatro: 'PAR1000 Aula Teatro'
    sociedad_italiana: 'Sociedad Italiana Unita'
    unnoba_alicia_moreau_de_justo: '"Edificio Alicia Moreau de Justo" - UNNOBA Escuela de Ciencias Económicas y Jurídicas'
    villa_alpina: 'Villa Alpina'
    pnlg: 'Parque Natural "Laguna de Gómez"'
    eac: 'Espacio a confirmar'
    plaza_25_de_mayo: "ESPACIO PÚBLICO (Plaza 25 de Mayo y cercanías)"
