---

metadatos:
  titulo: 'POSVERSO'
  dominio: 'posversobienal.com.ar'
  descripcion: 'POSVERSO . Bienal Internacional de Poesía Experimental de Argentina'
  claves: 'poesía, experimental, internacional, hotel dada, arte, posverso, art, poetry, junín, buenos aires, argentina'
  imagen_compartir: '/rec/grafica/logo-posverso_compartir.png'
  logo_posverso_a: '/rec/grafica/logo-posverso.svg'
  logo_posverso_b: '/rec/grafica/logo-posverso_completo.svg'
  texto_posverso: 'POSVERSO. Bienal Internacional de Poesía Experimental de Argentina.'
  texto_hoteldada: 'Hotel DaDA. Base de arte correo y poesía experimental.'
  logo_hoteldada_a: '/rec/grafica/logo-hoteldada.svg'
  logo_hoteldada_b: '/rec/grafica/logo-hoteldada_completo.svg'
  imagen_compartir: 'rec/grafica/logo-posverso_compartir.png'
  favicon: '/rec/grafica/favicon.svg'

emails:
  posverso: 'posversobienal@gmail.com'
  hoteldada: 'dadahotel@hotmail.com'

urls:
  formulario_convocatoria: 'https://docs.google.com/forms/d/e/1FAIpQLSdbD5bOK2aRV8d7-J8tomy5onPuFECn2KwHhEkLFMt8Ck-dvQ/viewform'
  posversobienal: 'https://posversobienal.com.ar/'
  posverso_instagram: 'https://www.instagram.com/posverso_bienal'
  posverso_youtube: 'https://www.youtube.com/@PosversoBienal'

  info_omar_khouri: 'http://www.antoniomiranda.com.br/poesia_visual/omar_khouri.html'
  info_cesar_espinosa: 'https://www.heterogenesis.com/H-45/EspinozaCas.htm'
  info_clemente_padin: 'https://www.museoreinasofia.es/sites/default/files/biblioteca/archivo-de-archivos/bibliografia_clemente_padin_2023.pdf'
  info_eduardo_antonio_vigo: 'http://www.cvaa.com.ar/03biografias/vigo_e.php'
  info_guillermo_deisler: 'http://guillermodeisler.cl/'
  info_dick_higgins: 'https://dickhiggins.org/'

  hoteldadabase: 'http://www.hoteldadabase.org/'
  hoteldada_facebook: 'https://www.facebook.com/profile.php?id=100063732964738'
  hoteldada_youtube: 'https://www.youtube.com/channel/UC4HS1EiLlyc4l0JDc8_BwFA'


menu:
  - titulo: 'ACERCA DE LA BIENAL'
    url: '/pag/acerca_de_la_bienal/'
  - titulo: 'POSVERSO BIENAL'
    url: '#'
    submenu:
      - titulo: 'Eje temático'
        url: '/pag/eje_tematico/'
      - titulo: 'Equipo curatorial'
        url: '/pag/equipo_curatorial/'
      - titulo: 'Artistas homenajeados'
        url: '/pag/artistas_homenajeados/'
      - titulo: 'Curadores invitados'
        url: '/pag/curadores_invitados/'
      - titulo: 'Socios estratégicos'
        url: '/pag/socios_estrategicos/'

  - titulo: 'PROGRAMA'
    url: '/pag/programa/'
    submenu:
      - titulo: 'Exhibición central'
        url: '/pag/exhibicion_central/'
      - titulo: 'Otras exhibiciones'
        url: '/pag/otras_exhibiciones/'
      - titulo: 'Proyectos colaterales'
        url: '/pag/proyectos_colaterales/'

  - titulo: 'SEDES'
    url: '/pag/sedes/'
  - titulo: 'CONVOCATORIA ABIERTA'
    url: '/pag/convocatoria_abierta/'
    submenu:
      - titulo: 'Comité de selección'
        url: '/pag/comite_de_seleccion/'
  - titulo: 'ARTISTAS INVITADOS'
    url: '/pag/artistas_invitados/'
  - titulo: 'CONTACTO'
    url: '/pag/contacto/'
